### ISSUE TITLE
Parametrized data types have their first ToSchema used everywhere

### ISSUE THREAD

**Issue by michalrus** [GetShopTV/swagger2#135] opened 2017-12-13 12:11 UTC
Hello!

If I have, say:

```hs
data SomeValue a = SomeValue
  { someInt :: Int
  , someA :: a
  } deriving (Show, Eq, Generic)

instance ToSchema a => ToSchema (SomeValue a)
```

… and then use both `SomeValue Text`, `SomeValue Bool` in the API definition, then, in the generated swagger.json, all instances of `SomeValue Bool` will be rendered as if they were `SomeValue Text`.

**Comment by phadej** [comment] 2017-12-13 13:41
"Duplicate" of https://github.com/GetShopTV/swagger2/issues

**Comment by michalrus** [comment] 2017-12-13 14:36
@phadej did you mean a particular one? Or are just most issues about that? :sweat_smile:

**Comment by phadej** [comment] 2017-12-13 14:40
I meant 
https://github.com/GetShopTV/swagger2/issues/94

**Comment by michalrus** [comment] 2018-01-29 12:00
So if one needs a quick fix, here’s what they can do:

```haskell
import qualified Data.Swagger                         as S
import           Data.Swagger.Schema                  (ToSchema (..))

data SearchResults a = SearchResults
  { total :: Int
  , results :: [a]
  } deriving (Eq, Show, Generic)

-- |Because of https://github.com/GetShopTV/swagger2/issues/135 we
-- need to add some suffixes to each schema name.
instance ToSchema a => ToSchema (SearchResults a) where
  declareNamedSchema proxy = do
    innerSchema <- S.declareSchemaRef (Proxy @a)
    (S.name %~ (++ Just "_Of_" ++ schemaRefName innerSchema)) <$>
      S.genericDeclareNamedSchema S.defaultSchemaOptions proxy

schemaRefName :: S.Referenced S.Schema -> Maybe Text
schemaRefName (S.Inline sch) = sch ^. S.title -- FIXME: almost always Nothing, find something better for “primitive” types
schemaRefName (S.Ref rf) = Just $ S.getReference rf
```

**Comment by fizruk** [comment] 2018-02-21 23:53
Closing as duplicate of #94.

**Closed by fizruk** 2018-02-21 23:53 UTC

**Comment by michalrus** [comment] 2018-03-19 13:26
Perhaps a better solution to the above one is in https://github.com/GetShopTV/swagger2/issues/94#issuecomment-374210562
